"""empty message

Revision ID: ce7a47327455
Revises: 4840df8eb256
Create Date: 2021-05-19 15:21:34.263977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7a47327455'
down_revision = '4840df8eb256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding', sa.Column('model_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embedding', 'model_name')
    # ### end Alembic commands ###
